# Generated by Django 5.2.8 on 2025-12-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='tipo_funcao',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo_funcao',
            field=models.CharField(choices=[('colaborador', 'Colaborador'), ('TI', 'TI'), ('Financiro', 'Financeiro'), ('Marketing', 'Marketing'), ('Juridíco', 'Juridíco'), ('Administrativo', 'Administrativo'), ('Projeto', 'Projeto')], default='colaborador', max_length=50),
        ),
    ]
