# Generated by Django 5.2.8 on 2025-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_cadastro_tipo_permissao_cadastro_tipo_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_funcao',
            field=models.CharField(choices=[('colaborador', 'Colaborador'), ('TI', 'TI'), ('Financiro', 'Financeiro'), ('Marketing', 'Marketing'), ('Juridíco', 'Juridíco'), ('Administrativo', 'Administrativo'), ('Projeto', 'Projeto')], default='administrativo', max_length=50),
        ),
    ]
