# Generated by Django 5.2.7 on 2025-11-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_cadastro_tipo_permissao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cadastro',
            table='cadastro',
        ),
    ]
