# Generated by Django 5.2.7 on 2025-10-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadeira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='status',
            field=models.CharField(choices=[('ocupado', 'Ocupado'), ('livre', 'Livre')], default='Livre', max_length=10),
        ),
    ]
