# Generated by Django 5.2.7 on 2025-11-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadeira', '0003_alter_cadeira_table'),
        ('sala', '0005_alter_sala_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='planta',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='sala',
            field=models.ForeignKey(choices=[('ocupada', 'Ocupada'), ('desocupada', 'Desocupada')], default='Livre', on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='sala.sala'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='status',
            field=models.CharField(choices=[('ocupada', 'Ocupada'), ('desocupada', 'Desocupada')], default='Livre', max_length=10),
        ),
    ]
