# Generated by Django 5.2.8 on 2025-11-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadeira', '0004_remove_cadeira_planta_cadeira_sala_and_more'),
        ('sala', '0005_alter_sala_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='sala.sala'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='status',
            field=models.CharField(choices=[('ocupada', 'Ocupada'), ('desocupada', 'Desocupada')], default='desocupada', max_length=10),
        ),
    ]
