site_name: Sistema de Gestão de Recursos - Softex
site_description: Sistema centralizado de gestão de recursos físicos para a Softex
site_author: Equipe REQ-2025.2-T01
site_url: https://seu-usuario.github.io/REQ-2025.2-T01-Softex

# Repository
repo_name: seu-usuario/REQ-2025.2-T01-Softex
repo_url: https://github.com/seu-usuario/REQ-2025.2-T01-Softex

# Copyright
copyright: Copyright &copy; 2025 Equipe REQ-2025.2-T01 - Softex

# Configuration
theme:
  name: material
  logo: assets/logo.png
  palette:
    # Tema claro fixo com cores da Softex
    - scheme: default
      primary: "#4A2BE1"
      accent: "#F142FB"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search

# Page tree
nav:
  - Início: index.md
  - Documentação do Projeto:
    - Introdução: introducao.md
    - Cenário Atual: cenario-atual.md
    - Solução Proposta: solucao-proposta.md
    - Estratégias de Engenharia: estrategias-engenharia.md
    - Cronograma e Entregas: cronograma-entregas.md
    - Interação Equipe-Cliente: interacao-equipe-cliente.md
    - Lições Aprendidas: licoes-aprendidas.md
    - Entregas: entregas.md
  - Guias Técnicos:
    - Instalação: instalacao.md
    - Uso: uso.md
  - Referências: referencias.md
  - Sobre: sobre.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seu-usuario
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/seu-usuario

# CSS personalizado
extra_css:
  - stylesheets/extra.css

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true
