site_name: REQ-2025.2-T01-Softex
site_description: Repositório de projeto da disciplina de REQ-T1 - 2025.2
site_author: Guilherme
site_url: https://seu-usuario.github.io/REQ-2025.2-T01-Softex

# Repository
repo_name: seu-usuario/REQ-2025.2-T01-Softex
repo_url: https://github.com/seu-usuario/REQ-2025.2-T01-Softex

# Copyright
copyright: Copyright &copy; 2025 Guilherme

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: seu-usuario/REQ-2025.2-T01-Softex
      branch: main

# Page tree
nav:
  - Início: index.md
  - Documentação:
    - Introdução: docs/introducao.md
    - Instalação: docs/instalacao.md
    - Uso: docs/uso.md
  - API:
    - Referência: api/referencia.md
  - Sobre: sobre.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seu-usuario
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/seu-usuario

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true
