# Generated by Django 5.2.7 on 2025-11-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='planta',
            table='planta',
        ),
    ]
