# Generated by Django 5.2.8 on 2025-12-02 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadeira', '0002_cadeira_pos_x_cadeira_pos_y'),
        ('reserva', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCadeira',
            fields=[
                ('id_reserva_cadeira', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='cadeira.cadeira')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_cadeira', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserva_cadeira',
                'ordering': ['data_inicio', 'hora_inicio'],
            },
        ),
    ]
