# Generated by Django 5.2.7 on 2025-10-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_rename_planta_id_sala_planta_alter_sala_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='sala_id',
            new_name='id_sala',
        ),
    ]
