# Generated by Django 5.2.7 on 2025-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_rename_sala_id_sala_id_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='status',
            field=models.CharField(choices=[('ocupada', 'Ocupada'), ('desocupada', 'Desocupada')], max_length=45),
        ),
    ]
