# Generated by Django 5.2.8 on 2025-12-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0004_rename_tipo_sala_sala_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaDeReuniao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sala de Reunião (simples)',
                'verbose_name_plural': 'Salas de Reunião (simples)',
                'db_table': 'sala_de_reuniao',
            },
        ),
    ]
