# Generated by Django 5.2.7 on 2025-11-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0004_alter_sala_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sala',
            table='sala',
        ),
    ]
